version: '3.9'

secrets:
  root_db_passwd:
    file: root_db_password.txt
  utente_db_passwd:
    file: utente_db_password.txt

networks:
  sequelize-net-ws-sql:
    driver: bridge

volumes:
  node_modules:

services:
  sql-sequelize:
    image: mysql:latest
    container_name: sql-sequelize
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_db_passwd
      MYSQL_DATABASE: dati-sequelize
      MYSQL_USER: utente
      MYSQL_PASSWORD_FILE: /run/secrets/utente_db_passwd
    networks:
      - sequelize-net-ws-sql
    ports:
      - 3311:3306
    secrets:
      - root_db_passwd
      - utente_db_passwd
  ws-progetto-prova:
    build: ./ws-server
    container_name: ws-sequelize
    working_dir: /app
    networks:
      - sequelize-net-ws-sql
    ports:
      - 3100:3100
    tty: true
    volumes:
      - node_modules:/app/node_modules
      - ./ws-server:/app
    secrets:
      - root_db_passwd
      - utente_db_passwd